// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DAL.DbContext;

#nullable disable

namespace PcAssemblyAssistant.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221024053816_AddHDDMigration")]
    partial class AddHDDMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DBO_DAL.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CoreAndArchitectureId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FrequencyAndOverclockingCapabilityId")
                        .HasColumnType("int");

                    b.Property<int?>("GPUId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParametrsId")
                        .HasColumnType("int");

                    b.Property<int?>("RAMoptionsId")
                        .HasColumnType("int");

                    b.Property<int?>("ThermalCharacteristicksId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoreAndArchitectureId");

                    b.HasIndex("CountryId");

                    b.HasIndex("FrequencyAndOverclockingCapabilityId");

                    b.HasIndex("GPUId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParametrsId");

                    b.HasIndex("RAMoptionsId");

                    b.HasIndex("ThermalCharacteristicksId");

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUCoreAndArchitecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Core")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("L2CacheSize")
                        .HasColumnType("int");

                    b.Property<int?>("L3CacheSize")
                        .HasColumnType("int");

                    b.Property<int>("MaxNumberOfThread")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfCores")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfEfficientCores")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPerformanceCores")
                        .HasColumnType("int");

                    b.Property<string>("ProcessTechnology")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitOfL2CacheSize")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfL3CacheSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CPUCoreAndArchitectures");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUFrequencyAndOverclockingCapability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("FreeMultiplier")
                        .HasColumnType("bit");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int?>("FrequencyOfEfficientCores")
                        .HasColumnType("int");

                    b.Property<int?>("MaxFrequencyInTurbo")
                        .HasColumnType("int");

                    b.Property<int?>("MaxFrequencyTurboOfEfficientCores")
                        .HasColumnType("int");

                    b.Property<int>("UnitFrequecy")
                        .HasColumnType("int");

                    b.Property<int?>("UnitFrequencyOfEfficientCores")
                        .HasColumnType("int");

                    b.Property<int?>("UnitMaxFrequencyInTurbo")
                        .HasColumnType("int");

                    b.Property<int?>("UnitMaxFrequencyTurboOfEfficientCores")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CPUFrequencyAndOverclockingCapabilities");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUGeneralParametrs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RealiseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CPUGeneralParametrs");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUGraphicsCore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ExecutiveBlocks")
                        .HasColumnType("int");

                    b.Property<int>("GPUCoreFreqency")
                        .HasColumnType("int");

                    b.Property<string>("GPUModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitOfGPUCoreFreqency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CPUGraphicsCores");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPURAMoptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MaxSuppMemory")
                        .HasColumnType("int");

                    b.Property<int>("MaximumRAMfrequency")
                        .HasColumnType("int");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfMemoryChanel")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMaxSuppMemory")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMaximumRAMfrequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CPURAMoptions");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUThermalCharacteristicks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MaxCPUtemprature")
                        .HasColumnType("int");

                    b.Property<int>("TDP")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfTDP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CPUThermalCharacteristicks");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ForMining")
                        .HasColumnType("bit");

                    b.Property<int?>("GPUConnectionId")
                        .HasColumnType("int");

                    b.Property<int?>("GPUCoolingSystemId")
                        .HasColumnType("int");

                    b.Property<int?>("GPUGeneralParametrsId")
                        .HasColumnType("int");

                    b.Property<int?>("GPUImageOutputId")
                        .HasColumnType("int");

                    b.Property<int?>("GPUVideoMemorySpecificId")
                        .HasColumnType("int");

                    b.Property<int?>("GPUVideoProcessorSpecificId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProducerCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("GPUConnectionId");

                    b.HasIndex("GPUCoolingSystemId");

                    b.HasIndex("GPUGeneralParametrsId");

                    b.HasIndex("GPUImageOutputId");

                    b.HasIndex("GPUVideoMemorySpecificId");

                    b.HasIndex("GPUVideoProcessorSpecificId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditPowerConnectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionFormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionInterface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecommendedPSU")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfRecommendedPSU")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GPUConnections");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUCoolingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CoolingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiquidCoolingRadiator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAndNumOfInstalledFans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GPUCoolingSystems");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUGeneralParametrs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GraphicProcessor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Microarchitecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProccessTechnology")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GPUGeneralParametrs");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUImageOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("DisplayPortVersion")
                        .HasColumnType("real");

                    b.Property<string>("MaxResolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfMonitorConnect")
                        .HasColumnType("int");

                    b.Property<string>("VideoConnectors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GPUImageOutputs");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUVideoMemorySpecific", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EffectiveMemoryFrequency")
                        .HasColumnType("int");

                    b.Property<string>("MaxMemoryBandwidth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoryBusWidht")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitOfEffectiveMemoryFrequency")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfVideoMemorySize")
                        .HasColumnType("int");

                    b.Property<int>("VideoMemorySize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GPUVideoMemorySpecific");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUVideoProcessorSpecific", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HardwareAcceleratedRayTracing")
                        .HasColumnType("int");

                    b.Property<int>("NominalFrequencyOfTheVideoChip")
                        .HasColumnType("int");

                    b.Property<int?>("NumOfROPs")
                        .HasColumnType("int");

                    b.Property<int>("NumOfTextureUnits")
                        .HasColumnType("int");

                    b.Property<int>("NumOfUniversalProcessors")
                        .HasColumnType("int");

                    b.Property<bool>("RayTracingSupport")
                        .HasColumnType("bit");

                    b.Property<float>("ShaderVersion")
                        .HasColumnType("real");

                    b.Property<int>("TensorCores")
                        .HasColumnType("int");

                    b.Property<int>("TurboFrequency")
                        .HasColumnType("int");

                    b.Property<int>("UnitNominalFreqOfTheVideoChip")
                        .HasColumnType("int");

                    b.Property<int>("UnitTurboFrequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GPUVideoProcessorSpecifics");
                });

            modelBuilder.Entity("DBO_DAL.Entities.HDD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HDDAdditionallyId")
                        .HasColumnType("int");

                    b.Property<int?>("HDDMechanicsAndReliabilityId")
                        .HasColumnType("int");

                    b.Property<int?>("HDDStorageDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("HDDAdditionallyId");

                    b.HasIndex("HDDMechanicsAndReliabilityId");

                    b.HasIndex("HDDStorageDeviceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HDDs");
                });

            modelBuilder.Entity("DBO_DAL.Entities.HDDAdditionally", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MaxOperatingTemp")
                        .HasColumnType("int");

                    b.Property<int>("MaxPowerConsumption")
                        .HasColumnType("int");

                    b.Property<int>("MinOperatingTemp")
                        .HasColumnType("int");

                    b.Property<int>("StandbyPowerConsumpiton")
                        .HasColumnType("int");

                    b.Property<int>("UnitMaxPowerConsumption")
                        .HasColumnType("int");

                    b.Property<int>("UnitStandbyPowerConsumpiton")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HDDAdditionallies");
                });

            modelBuilder.Entity("DBO_DAL.Entities.HDDMechanicsAndReliability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NoiseLevelDuring")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiseLevelInIdle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordingTechnology")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShockResistAtWork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HDDMechanicsAndReliabilities");
                });

            modelBuilder.Entity("DBO_DAL.Entities.HDDStorageDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CacheSize")
                        .HasColumnType("int");

                    b.Property<string>("IntarfaceHDD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterfaceBandwidth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxDataTransferRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OptForRAIDarrays")
                        .HasColumnType("bit");

                    b.Property<string>("SpindleSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitOfCacheSize")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfVolumeHDD")
                        .HasColumnType("int");

                    b.Property<int>("VolumeHDD")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HDDStorageDevices");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MBAudioId")
                        .HasColumnType("int");

                    b.Property<int?>("MBBackPanelId")
                        .HasColumnType("int");

                    b.Property<int?>("MBCollingAndPowerId")
                        .HasColumnType("int");

                    b.Property<int?>("MBExpensionSlotsId")
                        .HasColumnType("int");

                    b.Property<int?>("MBFormFactorId")
                        .HasColumnType("int");

                    b.Property<int?>("MBInternalConnectorsId")
                        .HasColumnType("int");

                    b.Property<int?>("MBRAMId")
                        .HasColumnType("int");

                    b.Property<int?>("MBStorageDeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("MBWebId")
                        .HasColumnType("int");

                    b.Property<int?>("MbCPUandChipsetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("MBAudioId");

                    b.HasIndex("MBBackPanelId");

                    b.HasIndex("MBCollingAndPowerId");

                    b.HasIndex("MBExpensionSlotsId");

                    b.HasIndex("MBFormFactorId");

                    b.HasIndex("MBInternalConnectorsId");

                    b.HasIndex("MBRAMId");

                    b.HasIndex("MBStorageDeviceId");

                    b.HasIndex("MBWebId");

                    b.HasIndex("MbCPUandChipsetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MBs");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBAudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SouncAdapterChipset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoundScheme")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MBAudios");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBBackPanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CountAndTypeUSB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountOfAnalogAudioJacks")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfNetworkPorts")
                        .HasColumnType("int");

                    b.Property<string>("DigitalAudioPorts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoOutputs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MBBackPanels");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBCollingAndPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ActiveCooling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUPowerConnector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainPowerConnctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassiveCooling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerPhases")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MBCollingAndPowers");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MbCPUandChipset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CPUStirpes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MbCPUandChipsets");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBExpensionSlots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountOfPCIExX16Slots")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfPCIExX1Slots")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfPCIorCrossfire")
                        .HasColumnType("int");

                    b.Property<string>("PCIExpressVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportedPCIorCrossfire")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MBExpensionSlots");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBFormFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MBFormFactor");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBInternalConnectors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CPUCoolerPowerConnector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FanConnectorsPin3")
                        .HasColumnType("int");

                    b.Property<int?>("FanConnectorsPin4")
                        .HasColumnType("int");

                    b.Property<string>("InternalUSBConnectors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LEDConnectorPin3")
                        .HasColumnType("int");

                    b.Property<int?>("LEDConnectorPin4")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MBInternalConnectors");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBRAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountOfRAMChannel")
                        .HasColumnType("int");

                    b.Property<int>("MaxRAMFrequency")
                        .HasColumnType("int");

                    b.Property<int>("MaximumMemory")
                        .HasColumnType("int");

                    b.Property<string>("RAMFormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAMType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotsCount")
                        .HasColumnType("int");

                    b.Property<int>("UnitMaxRAMFrequency")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMaxMemory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MBRAMs");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBStorageDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CountOfM2")
                        .HasColumnType("int");

                    b.Property<int>("CountOfPortsSATA")
                        .HasColumnType("int");

                    b.Property<string>("M2Connectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SupportedNVME")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MBStorageDevices");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBWeb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bluetooth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuiltInWifiAdapter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetAdapterChipset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetAdapterSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WiFiController")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MBWebs");
                });

            modelBuilder.Entity("DBO_DAL.Entities.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProducerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RAMKitVolumeAndCompositionId")
                        .HasColumnType("int");

                    b.Property<int?>("RAMPerformanceId")
                        .HasColumnType("int");

                    b.Property<int?>("RAMTimingsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RAMKitVolumeAndCompositionId");

                    b.HasIndex("RAMPerformanceId");

                    b.HasIndex("RAMTimingsId");

                    b.ToTable("RAMs");
                });

            modelBuilder.Entity("DBO_DAL.Entities.RAMKitVolumeAndComposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ECCMemory")
                        .HasColumnType("bit");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfModules")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RegisterMemory")
                        .HasColumnType("bit");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<int>("UnitTotalAmount")
                        .HasColumnType("int");

                    b.Property<int>("UnitVolumeOfOneModule")
                        .HasColumnType("int");

                    b.Property<int>("VolumeOfOneModule")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KitVolumeAndCompositions");
                });

            modelBuilder.Entity("DBO_DAL.Entities.RAMPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClockFrequency")
                        .HasColumnType("int");

                    b.Property<string>("IntelXMPprofiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitClockFrequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RAMPerformances");
                });

            modelBuilder.Entity("DBO_DAL.Entities.RAMTimings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CASLatency")
                        .HasColumnType("int");

                    b.Property<int>("RAStoCASDelay")
                        .HasColumnType("int");

                    b.Property<int>("RowPrechangeDelay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RAMTimings");
                });

            modelBuilder.Entity("DBO_DAL.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPU", b =>
                {
                    b.HasOne("DBO_DAL.Entities.CPUCoreAndArchitecture", "CoreAndArchitecture")
                        .WithMany("CPU")
                        .HasForeignKey("CoreAndArchitectureId");

                    b.HasOne("DBO_DAL.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("DBO_DAL.Entities.CPUFrequencyAndOverclockingCapability", "FrequencyAndOverclockingCapability")
                        .WithMany("CPU")
                        .HasForeignKey("FrequencyAndOverclockingCapabilityId");

                    b.HasOne("DBO_DAL.Entities.CPUGraphicsCore", "GPU")
                        .WithMany("CPU")
                        .HasForeignKey("GPUId");

                    b.HasOne("DBO_DAL.Entities.CPUGeneralParametrs", "Parametrs")
                        .WithMany("CPU")
                        .HasForeignKey("ParametrsId");

                    b.HasOne("DBO_DAL.Entities.CPURAMoptions", "RAMoptions")
                        .WithMany("CPU")
                        .HasForeignKey("RAMoptionsId");

                    b.HasOne("DBO_DAL.Entities.CPUThermalCharacteristicks", "ThermalCharacteristicks")
                        .WithMany("CPU")
                        .HasForeignKey("ThermalCharacteristicksId");

                    b.Navigation("CoreAndArchitecture");

                    b.Navigation("Country");

                    b.Navigation("FrequencyAndOverclockingCapability");

                    b.Navigation("GPU");

                    b.Navigation("Parametrs");

                    b.Navigation("RAMoptions");

                    b.Navigation("ThermalCharacteristicks");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPU", b =>
                {
                    b.HasOne("DBO_DAL.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("DBO_DAL.Entities.GPUConnection", "GPUConnection")
                        .WithMany("GPU")
                        .HasForeignKey("GPUConnectionId");

                    b.HasOne("DBO_DAL.Entities.GPUCoolingSystem", "GPUCoolingSystem")
                        .WithMany("GPU")
                        .HasForeignKey("GPUCoolingSystemId");

                    b.HasOne("DBO_DAL.Entities.GPUGeneralParametrs", "GPUGeneralParametrs")
                        .WithMany("GPU")
                        .HasForeignKey("GPUGeneralParametrsId");

                    b.HasOne("DBO_DAL.Entities.GPUImageOutput", "GPUImageOutput")
                        .WithMany("GPU")
                        .HasForeignKey("GPUImageOutputId");

                    b.HasOne("DBO_DAL.Entities.GPUVideoMemorySpecific", "GPUVideoMemorySpecific")
                        .WithMany("GPU")
                        .HasForeignKey("GPUVideoMemorySpecificId");

                    b.HasOne("DBO_DAL.Entities.GPUVideoProcessorSpecific", "GPUVideoProcessorSpecific")
                        .WithMany("GPU")
                        .HasForeignKey("GPUVideoProcessorSpecificId");

                    b.Navigation("Country");

                    b.Navigation("GPUConnection");

                    b.Navigation("GPUCoolingSystem");

                    b.Navigation("GPUGeneralParametrs");

                    b.Navigation("GPUImageOutput");

                    b.Navigation("GPUVideoMemorySpecific");

                    b.Navigation("GPUVideoProcessorSpecific");
                });

            modelBuilder.Entity("DBO_DAL.Entities.HDD", b =>
                {
                    b.HasOne("DBO_DAL.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("DBO_DAL.Entities.HDDAdditionally", "HDDAdditionally")
                        .WithMany("HDD")
                        .HasForeignKey("HDDAdditionallyId");

                    b.HasOne("DBO_DAL.Entities.HDDMechanicsAndReliability", "HDDMechanicsAndReliability")
                        .WithMany("HDD")
                        .HasForeignKey("HDDMechanicsAndReliabilityId");

                    b.HasOne("DBO_DAL.Entities.HDDStorageDevice", "HDDStorageDevice")
                        .WithMany("HDD")
                        .HasForeignKey("HDDStorageDeviceId");

                    b.Navigation("Country");

                    b.Navigation("HDDAdditionally");

                    b.Navigation("HDDMechanicsAndReliability");

                    b.Navigation("HDDStorageDevice");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MB", b =>
                {
                    b.HasOne("DBO_DAL.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("DBO_DAL.Entities.MBAudio", "MBAudio")
                        .WithMany("MB")
                        .HasForeignKey("MBAudioId");

                    b.HasOne("DBO_DAL.Entities.MBBackPanel", "MBBackPanel")
                        .WithMany("MB")
                        .HasForeignKey("MBBackPanelId");

                    b.HasOne("DBO_DAL.Entities.MBCollingAndPower", "MBCollingAndPower")
                        .WithMany("MB")
                        .HasForeignKey("MBCollingAndPowerId");

                    b.HasOne("DBO_DAL.Entities.MBExpensionSlots", "MBExpensionSlots")
                        .WithMany("MB")
                        .HasForeignKey("MBExpensionSlotsId");

                    b.HasOne("DBO_DAL.Entities.MBFormFactor", "MBFormFactor")
                        .WithMany("MB")
                        .HasForeignKey("MBFormFactorId");

                    b.HasOne("DBO_DAL.Entities.MBInternalConnectors", "MBInternalConnectors")
                        .WithMany("MB")
                        .HasForeignKey("MBInternalConnectorsId");

                    b.HasOne("DBO_DAL.Entities.MBRAM", "MBRAM")
                        .WithMany("MB")
                        .HasForeignKey("MBRAMId");

                    b.HasOne("DBO_DAL.Entities.MBStorageDevice", "MBStorageDevice")
                        .WithMany("MB")
                        .HasForeignKey("MBStorageDeviceId");

                    b.HasOne("DBO_DAL.Entities.MBWeb", "MBWeb")
                        .WithMany("MB")
                        .HasForeignKey("MBWebId");

                    b.HasOne("DBO_DAL.Entities.MbCPUandChipset", "MbCPUandChipset")
                        .WithMany("MB")
                        .HasForeignKey("MbCPUandChipsetId");

                    b.Navigation("Country");

                    b.Navigation("MBAudio");

                    b.Navigation("MBBackPanel");

                    b.Navigation("MBCollingAndPower");

                    b.Navigation("MBExpensionSlots");

                    b.Navigation("MBFormFactor");

                    b.Navigation("MBInternalConnectors");

                    b.Navigation("MBRAM");

                    b.Navigation("MBStorageDevice");

                    b.Navigation("MBWeb");

                    b.Navigation("MbCPUandChipset");
                });

            modelBuilder.Entity("DBO_DAL.Entities.RAM", b =>
                {
                    b.HasOne("DBO_DAL.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("DBO_DAL.Entities.RAMKitVolumeAndComposition", "RAMKitVolumeAndComposition")
                        .WithMany("RAM")
                        .HasForeignKey("RAMKitVolumeAndCompositionId");

                    b.HasOne("DBO_DAL.Entities.RAMPerformance", "RAMPerformance")
                        .WithMany("RAM")
                        .HasForeignKey("RAMPerformanceId");

                    b.HasOne("DBO_DAL.Entities.RAMTimings", "RAMTimings")
                        .WithMany("RAM")
                        .HasForeignKey("RAMTimingsId");

                    b.Navigation("Country");

                    b.Navigation("RAMKitVolumeAndComposition");

                    b.Navigation("RAMPerformance");

                    b.Navigation("RAMTimings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DBO_DAL.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DBO_DAL.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBO_DAL.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DBO_DAL.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUCoreAndArchitecture", b =>
                {
                    b.Navigation("CPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUFrequencyAndOverclockingCapability", b =>
                {
                    b.Navigation("CPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUGeneralParametrs", b =>
                {
                    b.Navigation("CPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUGraphicsCore", b =>
                {
                    b.Navigation("CPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPURAMoptions", b =>
                {
                    b.Navigation("CPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.CPUThermalCharacteristicks", b =>
                {
                    b.Navigation("CPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUConnection", b =>
                {
                    b.Navigation("GPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUCoolingSystem", b =>
                {
                    b.Navigation("GPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUGeneralParametrs", b =>
                {
                    b.Navigation("GPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUImageOutput", b =>
                {
                    b.Navigation("GPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUVideoMemorySpecific", b =>
                {
                    b.Navigation("GPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.GPUVideoProcessorSpecific", b =>
                {
                    b.Navigation("GPU");
                });

            modelBuilder.Entity("DBO_DAL.Entities.HDDAdditionally", b =>
                {
                    b.Navigation("HDD");
                });

            modelBuilder.Entity("DBO_DAL.Entities.HDDMechanicsAndReliability", b =>
                {
                    b.Navigation("HDD");
                });

            modelBuilder.Entity("DBO_DAL.Entities.HDDStorageDevice", b =>
                {
                    b.Navigation("HDD");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBAudio", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBBackPanel", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBCollingAndPower", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MbCPUandChipset", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBExpensionSlots", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBFormFactor", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBInternalConnectors", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBRAM", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBStorageDevice", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.MBWeb", b =>
                {
                    b.Navigation("MB");
                });

            modelBuilder.Entity("DBO_DAL.Entities.RAMKitVolumeAndComposition", b =>
                {
                    b.Navigation("RAM");
                });

            modelBuilder.Entity("DBO_DAL.Entities.RAMPerformance", b =>
                {
                    b.Navigation("RAM");
                });

            modelBuilder.Entity("DBO_DAL.Entities.RAMTimings", b =>
                {
                    b.Navigation("RAM");
                });
#pragma warning restore 612, 618
        }
    }
}
